import Dexie from "dexie";
import { db } from "./schema";
import type {
  BookmarkRow,
  CardRow,
  CoverRow,
  DeckColorConfig,
  DeckRow,
  DetectedCloze,
  PdfRow,
  Rect,
} from "../types";

export interface ImportParams {
  name: string;
  blob: Blob;
  pageCount: number;
  pageW: number;
  pageH: number;
  color: DeckColorConfig;
  clozes: DetectedCloze[];
  /** Stable cross-device id for the sync registry (generated by the caller on import). */
  bookId?: string;
}

function clozesToCards(
  clozes: DetectedCloze[],
  deckId: number,
  pdfId: number,
  now: number,
): CardRow[] {
  return clozes.map((cz) => ({
    deckId,
    pdfId,
    pageIndex: cz.pageIndex,
    rects: cz.rects,
    answerRect: cz.bbox,
    text: cz.text,
    createdAt: now,
  }));
}

export async function importDeck(p: ImportParams): Promise<number> {
  const now = Date.now();
  return db.transaction("rw", db.decks, db.pdfs, db.cards, async () => {
    const deckId = (await db.decks.add({
      name: p.name,
      createdAt: now,
      color: p.color,
      bookId: p.bookId,
    })) as number;
    const pdfId = (await db.pdfs.add({
      deckId,
      name: p.name,
      blob: p.blob,
      pageCount: p.pageCount,
      pageW: p.pageW,
      pageH: p.pageH,
    })) as number;
    const cards = clozesToCards(p.clozes, deckId, pdfId, now);
    for (let i = 0; i < cards.length; i += 500) {
      await db.cards.bulkAdd(cards.slice(i, i + 500));
    }
    return deckId;
  });
}

export function listDecks(): Promise<DeckRow[]> {
  return db.decks.orderBy("createdAt").reverse().toArray();
}

export function getDeck(deckId: number): Promise<DeckRow | undefined> {
  return db.decks.get(deckId);
}

export function getDeckPdf(deckId: number): Promise<PdfRow | undefined> {
  return db.pdfs.where("deckId").equals(deckId).first();
}

export function answerCount(deckId: number): Promise<number> {
  return db.cards.where("deckId").equals(deckId).count();
}

/** Add a manual answer mask on a page (user fixing a detection miss). Returns the new card id. */
export async function addCard(
  deckId: number,
  pdfId: number,
  pageIndex: number,
  rect: Rect,
): Promise<number> {
  return (await db.cards.add({
    deckId,
    pdfId,
    pageIndex,
    rects: [rect],
    answerRect: rect,
    text: "",
    createdAt: Date.now(),
  })) as number;
}

/** Remove a single answer mask (user fixing a false positive). */
export async function deleteCard(cardId: number): Promise<void> {
  await db.cards.delete(cardId);
}

export async function updateDeck(deckId: number, patch: Partial<DeckRow>): Promise<void> {
  await db.decks.update(deckId, patch);
}

/** Re-run detection for a deck under a new color config: replace all its answers. */
export async function redetectDeck(
  deckId: number,
  color: DeckColorConfig,
  clozes: DetectedCloze[],
): Promise<number> {
  const now = Date.now();
  return db.transaction("rw", db.decks, db.pdfs, db.cards, async () => {
    await db.decks.update(deckId, { color });
    const pdf = await db.pdfs.where("deckId").equals(deckId).first();
    if (!pdf?.id) throw new Error("PDFが見つかりません");
    await db.cards.where("deckId").equals(deckId).delete();
    const cards = clozesToCards(clozes, deckId, pdf.id, now);
    for (let i = 0; i < cards.length; i += 500) {
      await db.cards.bulkAdd(cards.slice(i, i + 500));
    }
    return cards.length;
  });
}

/** Lowest page index that has any answer (so the viewer/preview opens usefully). */
export async function firstAnswerPage(deckId: number): Promise<number> {
  const c = await db.cards
    .where("[deckId+pageIndex]")
    .between([deckId, Dexie.minKey], [deckId, Dexie.maxKey], true, true)
    .first();
  return c?.pageIndex ?? 0;
}

/** All answers on a given page (for the red-sheet viewer). */
export function cardsOnPage(deckId: number, pageIndex: number): Promise<CardRow[]> {
  return db.cards
    .where("[deckId+pageIndex]")
    .between([deckId, pageIndex], [deckId, pageIndex], true, true)
    .toArray();
}

/** All answers in a deck (grouped by page in the viewer). */
export function deckCards(deckId: number): Promise<CardRow[]> {
  return db.cards.where("deckId").equals(deckId).toArray();
}

export async function deleteDeck(deckId: number): Promise<void> {
  await db.transaction("rw", [db.decks, db.pdfs, db.cards, db.bookmarks, db.covers], async () => {
    await db.cards.where("deckId").equals(deckId).delete();
    await db.bookmarks.where("deckId").equals(deckId).delete();
    await db.pdfs.where("deckId").equals(deckId).delete();
    await db.covers.delete(deckId);
    await db.decks.delete(deckId);
  });
}

// ---- cover thumbnails (cached page-1 render, regenerable) ----

export function getCover(deckId: number): Promise<CoverRow | undefined> {
  return db.covers.get(deckId);
}

export async function setCover(deckId: number, blob: Blob): Promise<void> {
  await db.covers.put({ deckId, blob });
}

// ---- bookmarks (the user-built 目次) ----

export async function addBookmark(deckId: number, pageIndex: number, title: string): Promise<void> {
  await db.bookmarks.add({ deckId, pageIndex, title, createdAt: Date.now() });
}

/** Bulk-add bookmarks (e.g. imported from a PDF's built-in outline). */
export async function importBookmarks(
  deckId: number,
  items: { title: string; pageIndex: number }[],
): Promise<void> {
  if (!items.length) return;
  const now = Date.now();
  await db.bookmarks.bulkAdd(
    items.map((b) => ({ deckId, pageIndex: b.pageIndex, title: b.title, createdAt: now })),
  );
}

export function listBookmarks(deckId: number): Promise<BookmarkRow[]> {
  return db.bookmarks
    .where("[deckId+pageIndex]")
    .between([deckId, Dexie.minKey], [deckId, Dexie.maxKey], true, true)
    .toArray();
}

export async function renameBookmark(id: number, title: string): Promise<void> {
  await db.bookmarks.update(id, { title });
}

export async function deleteBookmark(id: number): Promise<void> {
  await db.bookmarks.delete(id);
}
